Step3 2023
lkhlkh23/java-racingcar pull request #1
Opened 2023-04-10 12:08 UTC by lkhlkh23

RacingGame Step3

2023-04-12 13:05 UTC, nokchax requested changes
직관적이지 않은 코드 
이해하기 쉽지 않은 코드

2023-04-12 13:05 UTC, nokchax commented on src/main/java/controller/RacingGame.java
> +        final int countOfTurns = RacingGameInputView.getInstance().getCountOfCarToMove();
이 변수도 레이싱 게임에 포함되어야 하지 않을까?

2023-04-12 13:05 UTC, nokchax commented on src/main/java/model/Position.java
> +    private final int location;
자동차의 위치를 표현하기 위한 값이자
자동차의 움직임을 결정하는 기준이 되기도 하는 값이라 혼란스럽네

혼란을 야기하는 코드는 좋은 코드라 할 수 있을까?

2023-04-12 13:05 UTC, nokchax commented on src/main/java/model/Position.java
> +            return new Position(this.location);
```suggestion
            return this;
```

2023-04-12 13:05 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +        this.position = this.position.move(position);
this.position.move(position);
새로운 포지션으로 현재 포지션을 옮긴다 라는 걸로 읽힘

그런데 실제 행위는 현재 포지션을 유지하던가, 현재 포지션에 + 1

2023-04-12 13:05 UTC, nokchax commented on src/main/java/model/RacingCarSet.java
> +    public static RacingCarSet of(final int countOfCars) {
음수 값 검증은?

2023-04-12 13:05 UTC, nokchax commented on src/main/java/model/RacingCarSet.java
> +        this.cars.forEach(c -> c.move(new Position()));
moveAll() 테스트는 어떻게 하나요?

2023-04-12 13:05 UTC, nokchax commented on src/main/java/model/RacingRoad.java
> +    private static final String ROAD = "-";
view와 관련된 로직이 도메인에 있네요

2023-04-12 13:05 UTC, nokchax commented on src/main/java/view/out/RacingGameOutputView.java
> +    public void printAllCarsPerTurn(final RacingCarSet cars, final RacingRoad road) {
모델을 뷰에 그대로 넘길때 우려되는 점은 없을까?

2023-04-12 13:05 UTC, nokchax commented on src/test/java/model/PositionTest.java
> +    @ValueSource(ints = {0, 1, 2, 3})
경계값 케이스만 테스트

2023-04-12 14:23 UTC, lkhlkh23 commented on src/main/java/model/Position.java
> +            return new Position(this.location);
Position 을 불변객체 컨셉으로 개발한것인데, 좋지 않는 코드인거야?!

2023-04-12 14:24 UTC, lkhlkh23 commented on src/main/java/model/RacingCar.java
> +        this.position = this.position.move(position);
I got it

2023-04-12 14:24 UTC, lkhlkh23 commented on src/main/java/model/RacingCarSet.java
> +    public static RacingCarSet of(final int countOfCars) {
I got it

2023-04-12 14:26 UTC, lkhlkh23 commented on src/main/java/model/RacingCarSet.java
> +        this.cars.forEach(c -> c.move(new Position()));
mock test 로 해야할 것 같은데, 테스트 가능한 구조로 고려해보겠음!

2023-04-12 14:30 UTC, lkhlkh23 commented on src/main/java/model/RacingRoad.java
> +    private static final String ROAD = "-";
model 의 결과값을 이용해서 출력하기 위한 용도이기 때문에 view 가 아니라고 생각했는데, model 과 view 를 나누는 기준을 무엇이라 고 생각해??!!

2023-04-12 14:31 UTC, lkhlkh23 commented on src/main/java/view/out/RacingGameOutputView.java
> +    public void printAllCarsPerTurn(final RacingCarSet cars, final RacingRoad road) {
아! model 바로 넘기기 보다는 view 에 전시할 수 있는 dto 형태로 넘기는 것이 더 좋을 것 같다!!

2023-04-12 14:31 UTC, lkhlkh23 commented on src/test/java/model/PositionTest.java
> +    @ValueSource(ints = {0, 1, 2, 3})
I got it

2023-04-12 14:32 UTC, lkhlkh23 commented on src/main/java/controller/RacingGame.java
> +        final int countOfTurns = RacingGameInputView.getInstance().getCountOfCarToMove();
RacingGame 이 controller 의 역할이라고 생각했기 때문에 view 와 model 관련된 처리를 RacingGame 에서 수행을 했는데...
controller 는 역시 main() 이라고 생각해야하나..?!

2023-04-12 14:33 UTC, lkhlkh23 commented on src/main/java/model/Position.java
> +    private final int location;
변수명 네이밍 할 때, 수정을 몇번 반복했던 부분이었는데 ...
역시 네이밍이 애매모호할 때는 올바른 클래스인지? 클래스를 다시 검토해야봐야겠다!

2023-04-13 12:21 UTC, lkhlkh23 commented on src/main/java/model/RacingCarSet.java
> +    public static RacingCarSet of(final int countOfCars) {
PositiveNumber 클래스 생성자를 통해 유효성 체크를 수행봤습니다! 😄

2023-04-14 15:16 UTC, nokchax requested changes
리뷰 남겼읍니다

2023-04-14 15:16 UTC, nokchax commented on src/main/java/model/PositiveNumber.java
> +            throw new InvalidRequestException(String.format("%d 는 자연수가 아닙니다.", num));
왜 checked exception을 사용하셨나요
IllegalArgumentException 같은거 쓰면 안 되나요?

2023-04-14 15:16 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +        return RacingRoad.getRoads(new PositiveNumber(location));
모델에서 뷰와 관련된 클래스에 의존하고 있네요

2023-04-14 15:16 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +        this.location = movement.canMove() ? this.location + 1 : this.location;
삼항 연산자는 쓰지마세요 if/else와 다름없습니다.

미션중에는 else문을 쓰지 말아주세요

2023-04-14 15:16 UTC, nokchax commented on src/main/java/controller/RacingGame.java
> +        final int countOfTurns = RacingGameInputView.getInstance().getCountOfCarToMove().getNum();
이것도 자동차 경주에 같이 들어가야 할 정보가 아닌가요?

2023-04-14 15:16 UTC, nokchax commented on src/main/java/model/Movement.java
> +    private final int distance;
움직임과 거리
개념이 정말 잘 이해되지 않는데 설명 좀 해주세요

2023-04-14 15:16 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +        this.location = location;
여기는 input값 검증 안해도 되나요?
입력값의 검증은 어디서 해야할까요?
입력 받는 순간에서 객체에 할당하는 순간까지 어디가 제일 좋다고 생각되시나요

2023-04-14 15:16 UTC, nokchax commented on src/main/java/model/RacingCarSet.java
> +            this.cars.get(i).move(movements.get(i));
여기가 뭐랄까 절차지향적인 코드로 보이는데, 개선 안 될까요?
Movement 객체 때문에 코드가 전반적으로 지저분한 거 같은데, 
Movement 클래스를 고집하시는 이유가 궁금합니다

2023-04-14 15:16 UTC, nokchax commented on src/main/java/model/RacingRoad.java
> +    private static final String ROAD = "-";
여기다 코멘트를 달아서 혼란을 드렸네요,
RacingCar에 RacingRoad가 존재해서 코멘트 드렸습니다.

2023-04-14 15:16 UTC, nokchax commented on src/test/java/model/RacingCarSetTest.java
> +        assertEquals(0, cars.getCars().get(0).getLocation());
assertThat(a).isEqualTo(b); 처럼 assertThat(~).~~ 를 사용하는 편은 어떤가요
assertEquals(기대값, 실제값); 으로 사용하는데 순서를 틀리게 넣는 실수를 할 수 있어서 안 좋다고 생각해요

2023-04-15 02:58 UTC, lkhlkh23 commented on src/main/java/model/Movement.java
> +    private final int distance;
'이동할 거리를 움직이다' 라는 개념으로 생각했습니다

2023-04-15 03:01 UTC, lkhlkh23 commented on src/main/java/model/RacingCar.java
> +        this.location = location;
사용자가 입력한 값에 의해 생성되는 객체가 아니기 때문에 검증로직을 넣지 않았습니다.
입력값의 검증은 생성자에서 하는것이 좋다고 생각합니다!

그렇기 때문에 아래 코드를 보시면 PositiveNumber 라는 클래스는 생성자를 통해 입력값의 유효성 체크를 수행했습니다!

2023-04-15 13:40 UTC, lkhlkh23 commented on src/main/java/model/RacingCar.java
> +        this.location = movement.canMove() ? this.location + 1 : this.location;
early return 하는 방식으로 변경했습니다!

2023-04-15 14:12 UTC, lkhlkh23 commented on src/main/java/model/RacingCar.java
> +        return RacingRoad.getRoads(new PositiveNumber(location));
model 과 view 는 서로에 대해 알지 못해야한다! 라는 부분은 동의합니다.
하지만, RacingRoad 는 model 이라고 생각했습니다.

대략적인 구성도를 README.md 에 추가했습니다.
- https://github.com/lkhlkh23/java-racingcar/blob/step3-2023/README.md

2023-04-15 14:16 UTC, lkhlkh23 commented on src/main/java/model/RacingCarSet.java
> +            this.cars.get(i).move(movements.get(i));
자동차는 움직이다/멈추다 만 수행하고, 움직임에 대한 난수 생성 및 움직임 여부를 결정하는 것은 별도 클래스에서 정의하는 것이 더 좋다고 생각해서 분리했습니다.

2023-04-15 14:32 UTC, nokchax requested changes
다시 해오세요, 맘에 들 때 까지 안 받아 줄거야

2023-04-15 14:32 UTC, nokchax commented on src/main/java/model/PositiveNumber.java
> +    public PositiveNumber(final int num) throws InvalidParameterException {
UncheckedException인데 굳이 명시한 이유는 뭔가요

2023-04-15 14:32 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +        this.location++;
```suggestion
        if(movement.canMove()) {
            this.location++;
        }
```

2023-04-15 14:32 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +    public String getMovingRoads() throws InvalidParameterException {
레이싱 카에서 뷰와 관련된거 제거달라고 몇번을 말씀드립니까요...

2023-04-15 14:32 UTC, nokchax commented on README.md
> +![architecture](architecture.png)
RacingLoad가 왜 모델인가요
레이싱 게임을 플레이하는데 필요한 로직이 들어가나요?
단순히 출력을 위한 객체아닌가요?

2023-04-15 14:34 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +        this.location = location;
지금이야 그런데, 도메인을 다양한 곳에서 쓰면 어떻게 그걸 보장할 수 있죠?
쓰다보면 의도와는 다르게 음수값을 넣는 개발자가 생길 수 도있을거 같은데?

2023-04-15 14:37 UTC, nokchax commented on src/main/java/model/Movement.java
> +    private final int distance;
아니죠, 이동할 거리를 움직이는게 아니라
이동 할지 말지를 정하는 클래스죠
distance는 이동 여부를 판단하는 기준에 불과하구요
이동할 거리가 아니지 않나요?

2023-04-15 14:38 UTC, nokchax commented on src/main/java/model/RacingCarSet.java
> +            this.cars.get(i).move(movements.get(i));
그건 동의하는데, 해당 클래스가 구조를 망친다는 의미입니다.

2023-04-15 14:43 UTC, lkhlkh23 commented on README.md
> +![architecture](architecture.png)
view 에 전시를 위한 형태로 만들기 위한 로직이 존재히기 때문에 model 에 더 가깝다고 생각했습니다.
view 에는 로직없이 단순 전시만 하는것이 맞다고 생각했습니다.

2023-04-15 14:44 UTC, lkhlkh23 commented on src/main/java/controller/RacingGame.java
> +        final int countOfTurns = RacingGameInputView.getInstance().getCountOfCarToMove().getNum();
RacingGame 은 controller 이기 때문에 inputview 를 호출해야한다고 생각했습니다!

2023-04-15 14:46 UTC, lkhlkh23 commented on src/main/java/model/Movement.java
> +    private final int distance;
자동차가 이동할 거리에 따라 움직임이거나 멈춘다
 -> racingCar 이 movement 의 값에 따라 움직이거나 멈춘다

2023-04-15 14:46 UTC, nokchax commented on README.md
> +![architecture](architecture.png)
그건 view를 위한 로직인데 어째서 그게 model이 되나요
그 로직이 없으면 레이싱 게임이 안 돌아가나요?
사용자에게 결과를 뿌려줄 때 만 문제되는거 안니가요?

2023-04-15 14:48 UTC, nokchax commented on src/main/java/controller/RacingGame.java
> +        final int countOfTurns = RacingGameInputView.getInstance().getCountOfCarToMove().getNum();
아뇨 countOfTurns 라는것도 레이싱 게임의 일부라는 거죠
Cars와 countOfTurns를 묶으면 좀 더 객체 지향적이지 않을까요?

2023-04-15 14:51 UTC, nokchax commented on src/main/java/model/Movement.java
> +    private final int distance;
값이라면 이해하기 쉬운데 distance 라고 하니까 혼란이 오는거 같네요

2023-04-16 02:43 UTC, nokchax requested changes
좀 더 객체지향 적으로 변경 됐습니다

2023-04-16 02:43 UTC, nokchax commented on build.gradle
> +    testImplementation 'org.mockito:mockito-inline:3.6.0'
목킹 사용하지 말고 테스트 해주세요
쓰지 말고 테스트 해봐야 더 많이 공부하게 됩니다.

2023-04-16 02:43 UTC, nokchax commented on src/main/java/model/RacingCar.java
>      public void move(final Movement movement) {
자동차의 움직임을 Movement 클래스 하나로만 제어할 수 있네요,
다양한 로직으로 차를 움직이고 싶다면 어떻게 해야하나요
예를들어 한번 움직였어면 한번 움직이지 않고 이전에 움직이지 않았으면 다음엔 움직이고

2023-04-16 02:43 UTC, nokchax commented on src/main/java/model/RacingRoundSet.java
> +            final RacingRound racingRound = RacingRound.of(getPreviousOrDefault(i));
previousRound.nextRound() 이런식으로 하는게 보기 좋을거 같은데

2023-04-16 02:43 UTC, nokchax commented on src/main/java/controller/RacingGame.java
> +        racingRounds.moveAllRounds();
모든 라운드를 한번에 움직이라 하지 말고
레이스가 끝나기 전까지 controller에서 제어할 수 있게 하면 어떨까요?

예를 들어 자동차 레이싱을 콘솔이 아니라 웹으로 만든다고 가정하고
각 라운드를 진행이 사용자의 버튼 클릭에 의해 진행되도록 한다면?

2023-04-16 02:43 UTC, nokchax commented on src/main/java/model/Movement.java
> +    private final int movingCondition;
이런식으로 하면 어떨까요?
```
private final Random random;

public Movement(final Random random) {
    this.random = random;
}

public boolean canMove() {
    return this.random.nextInt() >= LIMIT_OF_MIN_MOVEMENT;
}
```

2023-04-16 02:43 UTC, nokchax commented on src/main/java/model/PositiveNumber.java
> +public final class PositiveNumber {
Car에서 검증해주는데, 더이상 필요 없지 않을까요?
스트링을 입력받은 순간에 int형으로 파싱하는 걸로 대체하면 깔끔해 질거 같은데

2023-04-16 02:43 UTC, nokchax commented on src/main/java/model/RacingRoundSet.java
> +public final class RacingRoundSet {
클래스명이나 변수명에 컬렉션 이름(list, set, map...)을 사용하지 마세요, 객체지향적 사고를 방해하는 요소입니다.

2023-04-21 12:00 UTC, nokchax requested changes
re

2023-04-21 12:00 UTC, nokchax commented on src/main/java/controller/RacingGameManager.java
> +        RacingGameOutputView.getInstance().printRound(racingGame.getMovingDistanceRound(roundIndex));
RacingGameManager도 모델인데, view와 연관 되어있네요?

2023-04-21 12:00 UTC, nokchax commented on src/main/java/model/Movement.java
>      private final int movingCondition;
움직임을 판단할 때 random.nextInt() >= LIMIT_OF_MIN_MOVEMENT 로 판단할 수 있는데
movingCondition 없앨 수 있지 않나요? 지금처럼 사용하면 Random을 옮긴 이유가 크게 없는거 같아요

2023-04-21 12:00 UTC, nokchax commented on src/main/java/controller/RacingGameManager.java
> +        RacingGameOutputView.getInstance().printRound(racingGame.getMovingDistanceRound(roundIndex));
관련한 멘트를 몇번 남기는지 모르겠는데 그냥 직접 코멘트 다는게 나을거 같네요 출력은 main에서만 해주세요

2023-04-21 12:00 UTC, nokchax commented on src/test/java/controller/RacingGameManagerTest.java
> +class RacingGameManagerTest {
모델에 존재하는 모든 함수에 대해서 테스트 해주세요
생성자, 정적 팩토리 메서드 까지 모두요

2023-04-21 12:00 UTC, nokchax commented on src/main/java/model/Movement.java
>      private final int movingCondition;
movingConditiond을 제거하고 random.nextInt() >= LIMIT_OF_MIN_MOVEMENT 만으로 움직임을 판단하면
모든 자동차 객채에 동일한 Movement 를 넘겨도 되므로 코드가 단순해 지지 않을까요?

2023-04-21 12:00 UTC, nokchax commented on src/main/java/model/RacingCar.java
> +        if(movement.canMove()) {
전략패턴을 써먹어보는건 어떨까요

2023-04-21 12:00 UTC, nokchax commented on src/main/java/model/RacingGame.java
> +    private List<RacingRound> racingRounds;
라운드 정보를 가지지 말고 매 라운드가 끝날 때 마다 출력하면 코드가 많이 간결해 질거 같습니다

2023-04-23 12:01 UTC, nokchax approved these changes
깔끔하고 이해가기도 쉽네요,
코멘트 달아둔거 조금만 수정하고 다음 단계 가시죠

2023-04-23 12:01 UTC, nokchax commented on src/main/java/Application.java
> +        }
👍

2023-04-23 12:01 UTC, nokchax commented on src/test/java/model/RangeRandomTest.java
> +    @RepeatedTest(value = 100)
테스트는 반복이랑 관계없이 검증이 되어야 함

2023-04-23 12:01 UTC, nokchax commented on src/main/java/model/RandomMovement.java
> +    private final RangeRandom random;
RangeRandom 대신에 Random을 쓰면 안 될까?

2023-04-23 12:01 UTC, nokchax commented on src/test/java/model/RacingCarTest.java
> +        assertThat(car.getLocation()).isEqualTo(0);
```suggestion
        assertThat(car.getLocation()).isZero();
```

2023-04-23 12:53 UTC, merged