Step4 2023
lkhlkh23/java-racingcar pull request #2
Opened 2023-04-23 14:19 UTC by lkhlkh23

Step4 구현했습니다.

2023-04-23 14:20 UTC, lkhlkh23 commented on src/main/java/view/out/RacingGameOutputView.java
> +        for (final String name : playerLocations.keySet()) {
이름, 위치 정도만 전달하기 때문에 Map을 이용했는데, DTO가 더 적합하겠죠?!

2023-04-25 10:50 UTC, nokchax requested changes
별달리 코멘트 할게 없는거 같은데 조금만 수정후 재요청 해주세요

2023-04-25 10:50 UTC, nokchax commented on src/main/java/model/RacingGame.java
> +                   .filter(c -> c.getLocation() == maxLocation)
c와 같은 약어 쓰지 말아주세요, car를 써주세요
getLocation()와 같이 값을 꺼내서 무언가 판별하려 하지 말고, maxLocation값을 전달해서 직접 판별시키는 건 어떨까요?

2023-04-25 10:50 UTC, nokchax commented on src/main/java/model/RacingGame.java
> +    public Map<String, Integer> getRacingCarLocations() {
DTO 쓰는게 좋겠네요

2023-04-25 12:39 UTC, lkhlkh23 commented on src/main/java/model/RacingGame.java
> +                   .filter(c -> c.getLocation() == maxLocation)
약어는 제거했고, RacingCar 에 직접 메세지를 던져서 처리하는 방식으로 변경했습니다.

2023-04-25 12:50 UTC, lkhlkh23 commented on src/main/java/model/RacingGame.java
> +    public Map<String, Integer> getRacingCarLocations() {
model 에서 map 을 만들고, controller 에서 map -> dto 로 변경했습니다.

2023-04-26 13:21 UTC, nokchax approved these changes
다음 단계 궈궈

2023-04-26 13:25 UTC, merged